My_List = [1,2,3,4,5,6,7,8,9,10]
My_List.sort()#sort the elements in order
print(My_List)
My_List.reverse()
print(My_List)
My_List.pop()
print(My_List)
My_List.copy()
print(My_List)
My_List.clear()
print(My_List)
My_List.append(10)
print(My_List)
My_List.extend([11,12,13])
print(My_List)
My_List.count(10)
print(My_List)
My_List.remove(10)
print(My_List)
My_List.index(4)
print(My_List)
My_List.insert(2,10)
print(My_List)
My_List.pop(2)
print(My_List)
my_list1 = [1,2,3]
My_List.extend(my_list1)
print(My_List)
My_List.clear()
print(My_List)
